### ISSUE TITLE
Remove "Update View" button for dialogs that update in real-time

### ISSUE THREAD

**Issue by rohrlich** [emer/etable#22]
An example is the ePlot config dialog. Changing scale, plot type, etc all happens when you make the change. Having the update view button is confusing.

**Comment by rcoreilly** [comment]
The `UpdtView` is confusing in general -- if you mouse over to get tooltip, it tries to clarify that it only applies to the actual "StructView" *dialog* you're currently looking at, not some other view that it might be connected with.  Not sure what the best name would be to clarify that better?

**Comment by rcoreilly** [comment]
UpdtEdit?

**Comment by rohrlich** [comment]
I think the hover description is fine but why have it there at all if it is a no-op?

I don't like Update Edit, Update View is okay. Maybe Update Values? But as I said I don't like it there when it isn't functional, fine when it is functional.

**Comment by rcoreilly** [comment]
It is always functional!!  It always just updates *the dialog itself* (not the plot) -- most of the time the dialog is already updated, but sometimes the state of the struct gets updated by something else, and that is when it is needed.  e.g., looking at a Layer in a running sim.  The issue is that this is a fully generic feature of the StructView and applies to all such views.

We could try to add some kind of type-level property to enable it, so it only shows up on things that generally need it..

**Comment by rohrlich** [comment]
Yes not the plot, I got that a long time ago :)  I didn't think about the struct being updated behind the scenes. It doesn't hurt to have it do nothing in some cases so maybe you should just close the issue.
